language: ruby
os: linux
dist: xenial
cache:
  directories:
    - vendor/bundle
addons:
  firefox: latest
services:
  - xvfb
before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - sudo apt-get install -qq yarn
  - gem install bundler:2.0.2
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - tar -zxvf geckodriver-v0.24.0-linux64.tar.gz
  - sudo mv geckodriver /usr/local/bin/
install:
  - bundle config set path 'vendor/bundle'
  - bundle install
  - yarn install
script:
  - bundle exec rspec
notifications:
  email:
    recipients:
      - drabkirn@cdadityang.xyz
    on_success: never
    on_failure: always
branches:
  only: 
    - master
